name: Bug Report
description: Report a bug or issue with JIRA Copilot Assistant
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I run jira-create.sh, I get an error...
    validations:
      required: true

  - type: dropdown
    id: command
    attributes:
      label: Which command has the issue?
      options:
        - jira-create.sh
        - jira-groom.sh
        - jira-close.sh
        - jira-sync.sh
        - Other/Multiple
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Run command: ./scripts/jira-create.sh --summary "Test"
        2. See error: ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Ticket should be created successfully
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Got 401 Unauthorized error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Output
      description: Please paste any error messages or logs
      placeholder: |
        $ ./scripts/jira-create.sh --summary "Test"
        ❌ Error: ...
      render: shell
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: macOS 14.0, Ubuntu 22.04, etc.
    validations:
      required: true

  - type: input
    id: bash
    attributes:
      label: Bash Version
      description: Run `bash --version` and paste the first line
      placeholder: GNU bash, version 3.2.57
    validations:
      required: true

  - type: dropdown
    id: jira-type
    attributes:
      label: JIRA Type
      options:
        - JIRA Cloud
        - JIRA Server
        - JIRA Data Center
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have verified my .env configuration is correct
          required: true
        - label: I have the latest version of the scripts
          required: true
        - label: I have tried enabling DEBUG=true
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that might help
      placeholder: This only happens when using --features flag...
    validations:
      required: false
