name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature suggestion! Help us understand what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? What workflow is painful?
      placeholder: I'm frustrated when I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: Add a new command that...
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      options:
        - New command
        - Enhancement to existing command
        - New Copilot instruction
        - Integration with other tool
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Usage Example
      description: Show how you'd use this feature
      placeholder: |
        $ ./scripts/jira-<new-command>.sh --option value
        ✅ Success!
      render: shell
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other solutions or workarounds?
      placeholder: I tried using... but...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Small improvement
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      options:
        - label: I'd be willing to implement this feature myself
          required: false
        - label: I'd be willing to test this feature
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Anything else to help us understand this feature
      placeholder: This would help our team because...
    validations:
      required: false
