name: Feedback / General Question
description: Share feedback or ask a question
title: "[FEEDBACK] "
labels: ["feedback", "question"]
body:
  - type: markdown
    attributes:
      value: |
        We'd love to hear from you! Share your thoughts, questions, or suggestions.

  - type: dropdown
    id: feedback-type
    attributes:
      label: Feedback Type
      options:
        - General Question
        - Usage Feedback
        - Documentation Feedback
        - Training Feedback
        - Copilot Instructions Feedback
        - Other
    validations:
      required: true

  - type: textarea
    id: message
    attributes:
      label: Your Message
      description: What would you like to share?
      placeholder: I really like the way... / I have a question about...
    validations:
      required: true

  - type: dropdown
    id: experience
    attributes:
      label: Overall Experience
      description: How would you rate your experience so far?
      options:
        - "5 - Excellent"
        - "4 - Good"
        - "3 - Average"
        - "2 - Below Average"
        - "1 - Poor"
    validations:
      required: false

  - type: checkboxes
    id: usage
    attributes:
      label: Which features have you used?
      options:
        - label: jira-create.sh
        - label: jira-groom.sh
        - label: jira-close.sh
        - label: jira-sync.sh
        - label: GitHub Copilot integration

  - type: textarea
    id: improvements
    attributes:
      label: What could be better?
      description: How can we improve the JIRA Copilot Assistant?
      placeholder: It would be great if...
    validations:
      required: false

  - type: textarea
    id: praise
    attributes:
      label: What's working well?
      description: What do you love about the tool?
      placeholder: I love that...
    validations:
      required: false

  - type: checkboxes
    id: recommend
    attributes:
      label: Would you recommend this to colleagues?
      options:
        - label: Yes, I would recommend this tool
        - label: No, I would not recommend this tool

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Anything else you'd like to add
    validations:
      required: false
