name: CI - Full

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, docs/copilot-instructions-update ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10', '3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python }}-${{ hashFiles('**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python }}-

      - name: Install system deps (shellcheck)
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run shellcheck on scripts
        run: |
          shellcheck scripts/*.sh || true

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi

      - name: Run full pytest suite
        run: |
          pytest -q
