name: CI - tests

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test (pytest + shell smoke)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f mcp-server/requirements.txt ]; then pip install -r mcp-server/requirements.txt; fi

      - name: Run pytest (mcp-server)
        working-directory: ${{ github.workspace }}
        run: |
          set -euo pipefail
          if [ -d mcp-server ]; then
            python -m pytest -q mcp-server || true
          else
            echo "No mcp-server directory; skipping pytest"
          fi

      - name: Run shell smoke tests (converter)
        working-directory: ${{ github.workspace }}
        run: |
          set -euo pipefail
          if [ -x tests/test-converter.sh ]; then
            bash tests/test-converter.sh
          else
            echo "No converter test runner found or not executable; skipping"
          fi

  integration:
    name: Integration tests (manual)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run integration note
        run: |
          echo "This workflow is a placeholder for manual integration tests that require secrets."
