name: PR Coverage Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi

      - name: Run tests with coverage
        run: |
          python -m pytest --maxfail=1 --disable-warnings -q --cov=mcp-server --cov-report=term-missing
        continue-on-error: true

      - name: Upload coverage XML
        if: always()
        run: |
          python -m pip install coverage
          coverage xml -i -o coverage.xml || true
        continue-on-error: true

      - name: Check coverage threshold
        if: always()
        run: |
          python .github/scripts/check_coverage.py
