name: Spec linter

on:
  pull_request:
    paths:
      - 'specs/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make scripts executable
        run: chmod +x scripts/spec-lint.sh || true
      - name: Run spec lint
        run: |
          # find changed spec files in the PR
          git fetch origin main:refs/remotes/origin/main
          CHANGED=$(git diff --name-only origin/main...HEAD -- specs || true)
          if [[ -z "$CHANGED" ]]; then
            echo "No changed specs"
            exit 0
          fi
          echo "Changed specs: $CHANGED"
          # run linter
          for f in $CHANGED; do
            ./scripts/spec-lint.sh "$f" || exit 1
          done
